name: PiraChest Release Changelog

on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send release to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          username: "GitHub"
          footer_title: "PiraChest Changelog"
          reduce_headings: true
          content: "<@&1548027659337080903>"
